name: Elice-CI CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 가장 먼저, 저장소에 있는 파일을 가져와야 함 -> checkout
    # node.js 다운받아야 함.(버전 지정)
    # 의존성이 존재, 그걸 받아야 함(npm ci)
    # 테스트를 돌려서 확인
    # 이제 배포 돌리면 됨.
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: "sounbeom@gmail.com"
          heroku_app_name: "heroku-test-cd-sb"
